apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bookverse
type: Opaque
stringData:

  # DB_USERNAME: Ym9va3ZlcnNl # bookverse (echo -n "bookverse" | base64)
  # DB_PASSWORD: Ym9va3ZlcnNl # bXlfc2VjdXJlX3Bhc3N3b3Jk # my_secure_password
  
  JWT_REFRESH_SECRETS: "my-super-refresh-secret" 

  JWT_SECRET: test
  JWT_REFRESH_SECRET: super-secret-refresh

  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest



---
apiVersion: v1
kind: Secret
metadata:
  name: bookverse-postgresql-credentials
  namespace: bookverse
type: Opaque
stringData:
  # stringData allows plain text input; Kubernetes automatically base64 encodes it on apply
  db-name: bookverse_auth
  db-user: bookverse
  db-password: bookverse