apiVersion: v1
kind: Namespace
metadata:
  name: bookverse

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookverse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/goniusman/GitOps'
    targetRevision: master  # Changed from HEAD to your explicit branch name
    path: helm/bookverse/  # FIXED: Points to the exact folder where Chart.yaml lives
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookverse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-dashboards
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goniusman/GitOps.git
    targetRevision: master
    path: helm/argocd-apps/istio-addons # 🌟 Points to the flat, simple YAML folder we pulled earlier
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




