apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: istio-system
  labels:
    grafana_datasource: "1" # This label makes Grafana automatically inject these settings
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.istio-system.svc.cluster.local:9090
      isDefault: true

    - name: Loki
      type: loki
      access: proxy
      url: http://loki.istio-system.svc.cluster.local:3100

    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://tracing.istio-system.svc.cluster.local:80