apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: gateway
    targetRevision: 1.22.1
    helm:
      values: |
        # Disable autoscaling so replicaCount is respected
        autoscaling:
          enabled: false

        replicaCount: 1

        # Resource limits and requests must be assigned to the container block
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "300m"
            memory: "128Mi"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true