apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: gateway
    targetRevision: 1.22.1
    helm:
      # Keep these parameters at the root level as required by the chart
      values: |
        autoscaling:
          enabled: false

        replicaCount: 1

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "300m"
            memory: "128Mi"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # This bypasses the strict schema conflict between Helm and ArgoCD
      - SkipSchemaValidation=true