apiVersion: v1
kind: Service
metadata:
  name: review
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: review
    app.kubernetes.io/part-of: bookverse
    app.kubernetes.io/component: microservice
spec:
  ports:
    - name: http
      port: {{ .Values.review.service.port }}
      targetPort: {{ .Values.review.service.port }}
  selector:
    app: review