# http:
#   - fault:
#       abort:
#         percentage:
#           value: 20

#         httpStatus: 500
#       delay:
#         percentage:
#           value: 50

#         fixedDelay: 5s

#     route:
#       - destination:
#           host: book-service