apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: jaeger-permissive
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: jaeger # Check your jaeger pod labels using 'kubectl get pods -n istio-system --show-labels'
  mtls:
    mode: PERMISSIVE