# apiVersion: networking.istio.io/v1

# kind: VirtualService

# metadata:
#   name: book-service

# spec:
#   hosts:
#     - book-service

#   http:
#     - retries:
#         attempts: 3
#         perTryTimeout: 2s
#     - timeout: 5s
#       route:
#         - destination:
#             host: book-service