apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: istiod
    targetRevision: 1.22.1
    helm:
      values: |
        global:
          meshID: mesh1
          multiCluster:
            clusterName: minikube-cluster
        meshConfig:
          accessLogFile: /dev/stdout
          enableAutoMtls: true
          defaultConfig:
            proxyMetadata: {}
              # Enables Prometheus scraping natively via telemetry annotations
              # OUTPUT_CERTS: "/etc/istio-certs"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true