apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring

data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
    - job_name: kubernetes-pods

      kubernetes_sd_configs:
        - role: pod
          # api_server: https://192.168.49.2:8443
          # tls_config:
          #   insecure_skip_verify: true

      pipeline_stages:
        - cri: {}

      relabel_configs:

        # namespace
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace

        # pod
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod

        # container
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container

        # app
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app

        # 🔥 SINGLE CORRECT LOG PATH RULE
        - action: replace
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
          replacement: /var/log/containers/*$1*.log










      # - job_name: gateway-files
      #   static_configs:
      #     - targets:
      #         - localhost

      #       labels:
      #         app: gateway
      #         namespace: bookverse
      #         __path__: /logs/**/*.log