# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgresql-pv
#   namespace: bookverse
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/postgres" # This matches the Minikube internal mount path


# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgresql-pvc
#   namespace: bookverse
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   volumeName: postgresql-pv