apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    app: prometheus
spec:
  type: ExternalName
  # Format: <service-name>.<namespace>.svc.cluster.local
  externalName: monitoring-stack-kube-prom-prometheus.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
spec:
  type: ExternalName
  # Format: <service-name>.<namespace>.svc.cluster.local
  externalName: monitoring-stack-grafana.monitoring.svc.cluster.local