apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    app: prometheus
spec:
  type: ExternalName
  # Format: <service-name>.<namespace>.svc.cluster.local
  externalName: monitoring-stack-kube-prom-prometheus.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
spec:
  # type: ExternalName
  # Format: <service-name>.<namespace>.svc.cluster.local
  # externalName: monitoring-stack-grafana.monitoring.svc.cluster.local
  spec:
  ports:
  - name: http
    port: 3000
    targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: grafana
  namespace: istio-system
subsets:
- addresses:
  # Replace with the ClusterIP of your 'monitoring-stack-grafana' service
  - ip: 10.97.253.171
  ports:
  - port: 80