# helm/monitoring/loki-values.yaml
deploymentMode: Monolithic

singleBinary:
  replicas: 1

loki:
  useTestSchema: true
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
    
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

minio:
  enabled: false

test:
  enabled: false
lokiCanary:
  enabled: false
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# CHANGE THIS TO FALSE:
gateway:
  enabled: false