# helm/monitoring/loki-values.yaml
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: false # Keep it stateless for local minikube testing

loki:
  useTestSchema: true
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    path_prefix: /tmp/loki

    
  storage:
    type: filesystem
    # bucketNames:
    #   chunks: chunks
    #   ruler: ruler
  ruler:
    storage:
      type: local
      local:
        directory: /tmp/loki/rules

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

minio:
  enabled: false

test:
  enabled: false
lokiCanary:
  enabled: false
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# CHANGE THIS TO FALSE:
gateway:
  enabled: false