apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.applications.name } }
  namespace: { { .Values.global.namespace } }
  labels:
    app.kubernetes.io/name: { { .Values.applications.name } }
    app.kubernetes.io/part-of: bookverse
    app.kubernetes.io/component: microservice
spec:
  replicas: { { .Values.applications.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.applications.name } }
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      labels:
        app: { { .Values.applications.name } }
        app.kubernetes.io/name: { { .Values.applications.name } }
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: bookverse
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "3001"
    spec:
      containers:
        - name: { { .Values.applications.name } }
          image: "{{ .Values.applications.image.repository }}:{{ .Values.applications.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: { { .Values.applications.service.port } }
          envFrom:
            # - configMapRef:
            #     name: applications-config
            - configMapRef:
                name: app-config
            # - secretRef:
            #     name: applications-secrets
            - secretRef:
                name: app-secrets
            # - secretRef:
            #     name: bookverse-postgresql-credentials

          env:
            - name: "PORT"
              value: "{{ .Values.applications.service.port }}"
            - name: OTEL_SERVICE_NAME
              value: "{ { .Values.applications.name } }"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "http://jaeger.bookverse.svc.cluster.local:4317"

          readinessProbe:
            httpGet:
              path: /health/ready
              port: { { .Values.applications.service.port } }
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: { { .Values.applications.service.port } }
            initialDelaySeconds: 30
            periodSeconds: 15

          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
