apiVersion: v1
kind: Namespace
metadata:
  name: bookverse
  # labels:
  #   # 🌟 THIS LINE TELLS ISTIO TO TAKE CONTROL OF THIS NAMESPACE
  #   istio-injection: enabled


---
# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: bookverse
# spec:
#   mtls:
#     mode: PERMISSIVE

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: admin-user-secret
#   namespace: kubernetes-dashboard
#   annotations:
#     kubernetes.io/service-account.name: admin-user
# type: kubernetes.io/service-account-token