apiVersion: v1
kind: Service
metadata:
  name: { { .Values.applications.name } }
  namespace: { { .Values.global.namespace } }
  labels:
    app.kubernetes.io/name: { { .Values.applications.name } }
    app.kubernetes.io/part-of: { { .Values.global.namespace } }
    app.kubernetes.io/component: microservice
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  #   prometheus.io/port: "3001"
spec:
  selector:
    app.kubernetes.io/name: { { .Values.applications.name } }
  # type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.applications.service.port }}
      targetPort: {{ .Values.applications.service.port }}
      # nodePort: 30000 # minikube service serviceName than will assign ip
    # - name: metrics 
    #   port: {{ .Values.applications.service.port }}
    #   targetPort: {{ .Values.applications.service.targetPort }}
  # selector:
  #   app: applications