---
environment: "production"
gitops_repo_branch: "main" # ArgoCD tracks your stable branch

# Production scale requirements 
postgresql_architecture: "replication" 
rabbitmq_replica_count: 3             

# Production secrets
db_password: "SuperSecretEnterpriseDBPassword123!"
rabbitmq_password: "SecureRabbitMQPassword2026!"