# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: review
#   namespace: {{ .Values.global.namespace }}
# spec:
#   replicas: {{ .Values.review.replicaCount }}
#   selector:
#     matchLabels:
#       app: review
#   template:
#     metadata:
#       annotations:
#         proxy.istio.io/config: |
#           holdApplicationUntilProxyStarts: true
#       labels:
#         app: review
#         app.kubernetes.io/name: review
#         app.kubernetes.io/component: microservice
#         app.kubernetes.io/part-of: bookverse
#     spec:
#       containers:
#         - name: review
#           image: "{{ .Values.review.image.repository }}:{{ .Values.review.image.tag }}"
#           imagePullPolicy: Always
#           ports:
#             - containerPort: {{ .Values.review.service.port }}

#           envFrom:
#             # - configMapRef:
#             #     name: review-config
#             - configMapRef:
#                 name: app-config
#             # - secretRef:
#             #     name: review-secrets
#             - secretRef:
#                 name: app-secrets
#           env:
#             - name: "PORT"
#               value: "{{ .Values.review.service.port }}"
#             - name: OTEL_SERVICE_NAME
#               value: "review"
#             # - name: OTEL_EXPORTER_OTLP_ENDPOINT
#             #   value: "http://jaeger.bookverse.svc.cluster.local:4317"
#             - name: "MONGO_URL"
#               value: "mongodb://mongodb:27017/bookverse_review"

#           readinessProbe:
#             httpGet:
#               path: /health/ready
#               port: {{ .Values.review.service.port }}

#           livenessProbe:
#             httpGet:
#               path: /health/live
#               port: {{ .Values.review.service.port }}

#           resources:
#             requests:
#               cpu: 20m
#               memory: 64Mi
#             limits:
#               cpu: 200m
#               memory: 256Mi

              