location /books {
    proxy_pass http://book_cluster;
    proxy_set_header Host $host;
    proxy_set_header X-Request-ID $request_id;
    proxy_set_header X-Real-IP $remote_addr;
    
    # Fail-safe circuit break configuration
    proxy_next_upstream error timeout http_502 http_503;
    proxy_next_upstream_tries 2;
}