apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-kubernetes-discovery
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-kubernetes-discovery-binding
subjects:
  - kind: ServiceAccount
    # Update this name if you are deploying Alloy using a specific ServiceAccount
    name: default 
    namespace: observability
roleRef:
  kind: ClusterRole
  name: alloy-kubernetes-discovery
  apiGroup: rbac.authorization.k8s.io