apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookverse-microservices
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: bookverse

  namespaceSelector:
    matchNames:
      - bookverse

  endpoints:
    - port: http
      path: /metrics
      interval: 15s