apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-slo-rules
  namespace: observability
spec:
  groups:
    - name: slos
      rules:

      # ERROR RATE
      - record: job:http_requests:error_rate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m]))
            / sum(rate(http_requests_total[5m]))

      # LATENCY (p95)
      - record: job:http_requests:p95_latency
        expr: histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket[5m])) by (le))