###( BooK Service)

POST http://gateway.local/books HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NmUxZTZkLWJmZmItNDIwMi05MjUzLWU2YWJhZmM0NGY1MyIsImVtYWlsIjoiYWRtaW5AZW50ZXJwcmlzZS5jb20iLCJyb2xlcyI6WyJhZG1pbmlzdHJhdG9yIl0sInBlcm1pc3Npb25zIjpbInVzZXI6Y3JlYXRlIiwidXNlcjpyZWFkIiwidXNlcjpyZWFkX29uZSIsInVzZXI6dXBkYXRlIiwidXNlcjpkZWxldGUiLCJib29rOmNyZWF0ZSIsImJvb2s6cmVhZCIsImJvb2s6cmVhZF9vbmUiLCJib29rOnVwZGF0ZSIsImJvb2s6ZGVsZXRlIiwib3JkZXI6Y3JlYXRlIiwib3JkZXI6Z2V0Iiwib3JkZXI6dXBkYXRlIiwib3JkZXI6ZGVsZXRlIiwicmV2aWV3OmNyZWF0ZSIsInJldmlldzpyZWFkIiwicmV2aWV3OnJlYWRfb25lIiwicmV2aWV3OmJvb2tfaWQiLCJyZXZpZXc6dXBkYXRlIiwicmV2aWV3OmRlbGV0ZSJdLCJpYXQiOjE3ODQ3OTY0MTMsImV4cCI6MTc4NTQwMTIxM30.mwqY0LGQ5G6evHenytbp2MHj-7XebfTgbZaioCQFqY0

{
    "title": "Third Book",
    "author": "Goni",
    "description": "Second. interesting description is here",
    "price": 23,
    "quantity": 40,
    "isPublished" : false
}

####
GET http://gateway.local/books HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NmUxZTZkLWJmZmItNDIwMi05MjUzLWU2YWJhZmM0NGY1MyIsImVtYWlsIjoiYWRtaW5AZW50ZXJwcmlzZS5jb20iLCJyb2xlcyI6WyJhZG1pbmlzdHJhdG9yIl0sInBlcm1pc3Npb25zIjpbInVzZXI6Y3JlYXRlIiwidXNlcjpyZWFkIiwidXNlcjpyZWFkX29uZSIsInVzZXI6dXBkYXRlIiwidXNlcjpkZWxldGUiLCJib29rOmNyZWF0ZSIsImJvb2s6cmVhZCIsImJvb2s6cmVhZF9vbmUiLCJib29rOnVwZGF0ZSIsImJvb2s6ZGVsZXRlIiwib3JkZXI6Y3JlYXRlIiwib3JkZXI6Z2V0Iiwib3JkZXI6dXBkYXRlIiwib3JkZXI6ZGVsZXRlIiwicmV2aWV3OmNyZWF0ZSIsInJldmlldzpyZWFkIiwicmV2aWV3OnJlYWRfb25lIiwicmV2aWV3OmJvb2tfaWQiLCJyZXZpZXc6dXBkYXRlIiwicmV2aWV3OmRlbGV0ZSJdLCJpYXQiOjE3ODQ3OTY0MTMsImV4cCI6MTc4NTQwMTIxM30.mwqY0LGQ5G6evHenytbp2MHj-7XebfTgbZaioCQFqY0


###
GET http://gateway.local/books/6a4d05e6d030f574f8d1ec2a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NmUxZTZkLWJmZmItNDIwMi05MjUzLWU2YWJhZmM0NGY1MyIsImVtYWlsIjoiYWRtaW5AZW50ZXJwcmlzZS5jb20iLCJyb2xlcyI6WyJhZG1pbmlzdHJhdG9yIl0sInBlcm1pc3Npb25zIjpbInVzZXI6Y3JlYXRlIiwidXNlcjpyZWFkIiwidXNlcjpyZWFkX29uZSIsInVzZXI6dXBkYXRlIiwidXNlcjpkZWxldGUiLCJib29rOmNyZWF0ZSIsImJvb2s6cmVhZCIsImJvb2s6cmVhZF9vbmUiLCJib29rOnVwZGF0ZSIsImJvb2s6ZGVsZXRlIiwib3JkZXI6Y3JlYXRlIiwib3JkZXI6Z2V0Iiwib3JkZXI6dXBkYXRlIiwib3JkZXI6ZGVsZXRlIiwicmV2aWV3OmNyZWF0ZSIsInJldmlldzpyZWFkIiwicmV2aWV3OnJlYWRfb25lIiwicmV2aWV3OmJvb2tfaWQiLCJyZXZpZXc6dXBkYXRlIiwicmV2aWV3OmRlbGV0ZSJdLCJpYXQiOjE3ODQ3OTY0MTMsImV4cCI6MTc4NTQwMTIxM30.mwqY0LGQ5G6evHenytbp2MHj-7XebfTgbZaioCQFqY0


###
PUT http://gateway.local/books/6a4d05e6d030f574f8d1ec2a HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NmUxZTZkLWJmZmItNDIwMi05MjUzLWU2YWJhZmM0NGY1MyIsImVtYWlsIjoiYWRtaW5AZW50ZXJwcmlzZS5jb20iLCJyb2xlcyI6WyJhZG1pbmlzdHJhdG9yIl0sInBlcm1pc3Npb25zIjpbInVzZXI6Y3JlYXRlIiwidXNlcjpyZWFkIiwidXNlcjpyZWFkX29uZSIsInVzZXI6dXBkYXRlIiwidXNlcjpkZWxldGUiLCJib29rOmNyZWF0ZSIsImJvb2s6cmVhZCIsImJvb2s6cmVhZF9vbmUiLCJib29rOnVwZGF0ZSIsImJvb2s6ZGVsZXRlIiwib3JkZXI6Y3JlYXRlIiwib3JkZXI6Z2V0Iiwib3JkZXI6dXBkYXRlIiwib3JkZXI6ZGVsZXRlIiwicmV2aWV3OmNyZWF0ZSIsInJldmlldzpyZWFkIiwicmV2aWV3OnJlYWRfb25lIiwicmV2aWV3OmJvb2tfaWQiLCJyZXZpZXc6dXBkYXRlIiwicmV2aWV3OmRlbGV0ZSJdLCJpYXQiOjE3ODQ3OTY0MTMsImV4cCI6MTc4NTQwMTIxM30.mwqY0LGQ5G6evHenytbp2MHj-7XebfTgbZaioCQFqY0

{
    "title": "First Book update",
    "author": "Osman Goni",
    "description": "Interesting description is here",
    "price": 30,
    "quantity": 40,
    "isPublished" : false
}

####
DELETE http://gateway.local/books/6a1bdebe614ce908eaa87fad HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NmUxZTZkLWJmZmItNDIwMi05MjUzLWU2YWJhZmM0NGY1MyIsImVtYWlsIjoiYWRtaW5AZW50ZXJwcmlzZS5jb20iLCJyb2xlcyI6WyJhZG1pbmlzdHJhdG9yIl0sInBlcm1pc3Npb25zIjpbInVzZXI6Y3JlYXRlIiwidXNlcjpyZWFkIiwidXNlcjpyZWFkX29uZSIsInVzZXI6dXBkYXRlIiwidXNlcjpkZWxldGUiLCJib29rOmNyZWF0ZSIsImJvb2s6cmVhZCIsImJvb2s6cmVhZF9vbmUiLCJib29rOnVwZGF0ZSIsImJvb2s6ZGVsZXRlIiwib3JkZXI6Y3JlYXRlIiwib3JkZXI6Z2V0Iiwib3JkZXI6dXBkYXRlIiwib3JkZXI6ZGVsZXRlIiwicmV2aWV3OmNyZWF0ZSIsInJldmlldzpyZWFkIiwicmV2aWV3OnJlYWRfb25lIiwicmV2aWV3OmJvb2tfaWQiLCJyZXZpZXc6dXBkYXRlIiwicmV2aWV3OmRlbGV0ZSJdLCJpYXQiOjE3ODQ3OTY0MTMsImV4cCI6MTc4NTQwMTIxM30.mwqY0LGQ5G6evHenytbp2MHj-7XebfTgbZaioCQFqY0
