apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      labels:
        app: order
        app.kubernetes.io/name: order
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: bookverse
    spec:
      containers:
        - name: order
          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.order.service.port }}

          envFrom:
            # - configMapRef:
            #     name: order-config
            - configMapRef:
                name: app-config
            # - secretRef:
            #     name: order-secrets
            - secretRef:
                name: app-secrets

          env:
            - name: "PORT"
              value: "{{ .Values.order.service.port }}"
            - name: OTEL_SERVICE_NAME
              value: "order"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "http://jaeger.bookverse.svc.cluster.local:4317"
            - name: "MONGO_URL"
              value: "mongodb://mongodb:27017/bookverse_orders"

          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.order.service.port }}

          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.order.service.port }}

          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi