apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: {{ .Values.global.namespace }}
spec:
  # ports:
  #   - port: {{ .Values.notification.service.port }}
  #     targetPort: {{ .Values.notification.service.port }}
  selector:
    app: notification